/* ============================================================
   奢眼 SHÉYAN · 二奢商家行情与产品智库  —— 演示数据文件
   数据口径：2026年10月公开渠道行情整理（95新、全套附件）
   说明：均为参考区间，实际以实物鉴定与当日实时报价为准
   ============================================================ */

const META = {
  appName: "奢眼",
  appEn: "SHÉYAN",
  slogan: "二奢商家的行情参谋",
  dataDate: "2026-10-08",
  dataScope: "95新 · 全套附件",
  disclaimer: "行情数据整理自2026年10月公开渠道（覆盖上海/北京/天津/成都等地回收行情），为参考区间。实际回收/零售价受年份、成色、附件、五金状态影响，以实物鉴定与当日实时报价为准。"
};

/* ---------- 品牌总览 ---------- */
const BRANDS = [
  { id: "hermes",   name: "爱马仕",   en: "Hermès",          cat: "包袋", tier: "顶奢", mono: "H",  color: "#B8763E", ret: 138, trend: 6 },
  { id: "chanel",   name: "香奈儿",   en: "Chanel",          cat: "包袋", tier: "顶奢", mono: "CC", color: "#1A1A1A", ret: 82,  trend: 3 },
  { id: "lv",       name: "路易威登", en: "Louis Vuitton",   cat: "包袋", tier: "一线", mono: "LV", color: "#6B4A2F", ret: 68,  trend: -8 },
  { id: "dior",     name: "迪奥",     en: "Dior",            cat: "包袋", tier: "一线", mono: "D",  color: "#8A8F98", ret: 48,  trend: -5 },
  { id: "gucci",    name: "古驰",     en: "Gucci",           cat: "包袋", tier: "一线", mono: "G",  color: "#2E5E4E", ret: 55,  trend: -4 },
  { id: "rolex",    name: "劳力士",   en: "Rolex",           cat: "腕表", tier: "硬奢", mono: "♛",  color: "#0F6B3E", ret: 92,  trend: -4 },
  { id: "patek",    name: "百达翡丽", en: "Patek Philippe",  cat: "腕表", tier: "硬奢", mono: "PP", color: "#1B3A6B", ret: 115, trend: 4 },
  { id: "ap",       name: "爱彼",     en: "Audemars Piguet", cat: "腕表", tier: "硬奢", mono: "AP", color: "#2B2B2B", ret: 88,  trend: 4 },
  { id: "omega",    name: "欧米茄",   en: "Omega",           cat: "腕表", tier: "一线", mono: "Ω",  color: "#0A4C8C", ret: 62,  trend: -13 },
  { id: "cartier",  name: "卡地亚",   en: "Cartier",         cat: "腕表", tier: "一线", mono: "C",  color: "#8C1D32", ret: 72,  trend: 2 },
  { id: "longines", name: "浪琴",     en: "Longines",        cat: "腕表", tier: "入门", mono: "L",  color: "#1F4E79", ret: 38,  trend: -6 },
  { id: "tudor",    name: "帝舵",     en: "Tudor",           cat: "腕表", tier: "入门", mono: "T",  color: "#7A1F1F", ret: 68,  trend: 0 },

  { id: "vca",      name: "梵克雅宝", en: "Van Cleef & Arpels", cat: "首饰", tier: "高珠", mono: "VCA", color: "#123B2C", ret: 74, trend: 3 },
  { id: "cartier_j",name: "卡地亚首饰", en: "Cartier Jewellery", cat: "首饰", tier: "高珠", mono: "CJ", color: "#8C1D32", ret: 75, trend: 2 },
  { id: "bvlgari",  name: "宝格丽",   en: "Bvlgari",         cat: "首饰", tier: "高珠", mono: "BV", color: "#B08D2E", ret: 60,  trend: -2 },
  { id: "tiffany",  name: "蒂芙尼",   en: "Tiffany & Co.",   cat: "首饰", tier: "一线", mono: "T&", color: "#4C8CBF", ret: 52,  trend: -5 },
  { id: "ysl",      name: "圣罗兰",   en: "Saint Laurent",   cat: "包袋", tier: "一线", mono: "Y",  color: "#1B1B1B", ret: 48,  trend: -3 },
  { id: "loewe",    name: "罗意威",   en: "LOEWE",           cat: "包袋", tier: "一线", mono: "LW", color: "#4A3423", ret: 52,  trend: -2 },
  { id: "celine",   name: "赛琳",     en: "CELINE",          cat: "包袋", tier: "一线", mono: "CE", color: "#37423D", ret: 45,  trend: -4 },
  { id: "vacheron", name: "江诗丹顿", en: "Vacheron Constantin", cat: "腕表", tier: "硬奢", mono: "VC", color: "#1E3F8F", ret: 85, trend: 3 }
];

/* ---------- 品牌详情补充 ---------- */
const BRAND_DETAIL = {
  hermes: {
    intro: "1837年创立于巴黎，以马具起家，至今坚持手工缝制。BKC（Birkin/Kelly/Constance）构成品牌价值核心，年产量极低，配货制形成天然稀缺。二手市场平均保值率断层第一。",
    rules: [
      "配货比：金刚色新客普遍 1:1.5~1:2，熟客可降至 1:0.8~1:1.2（无官方明文比例）",
      "丝巾/成衣/珠宝 100% 计入配货额度；香水、彩妆多数门店已明确排除；小皮具多店已剔除",
      "金刚色 = 黑金、金棕、大象灰；黄金尺寸 = Birkin 25/30、Kelly 25/28",
      "全套附件（盒、防尘袋、锁匙、雨衣、票）可提价 10%~20%；裸包折价明显",
      "每年 1 月调价，近年年均涨幅 5%~9%"
    ],
    risks: ["稀有皮（鳄鱼/鸵鸟）配货高、保养贵、流通窄，新手不建议", "35/40 大尺寸难转手", "冷门色（亮蓝、玫红）折价快"]
  },
  chanel: {
    intro: "经典 CF 与 2.55 是品牌形象产品，也是每年调价的价格锚点。自 2019 年至今中号从 3.81 万涨至区间 8.5 万以上，五年翻倍。二手流通速度极快，黑金配色是市场定海神针。",
    rules: [
      "每年 3 月、9 月两轮全球调价，年度总涨幅 15%~22%",
      "2021 年起序列号改为 NFC 芯片，旧款为镭射标 + 身份卡",
      "黑金 > 黑银 > 季节色；鱼子酱皮（Caviar）比小羊皮贵约 1000~2000 元且更耐磨",
      "季节款流通性差，折价常至公价 5~6 折，收包需谨慎"
    ],
    risks: ["小羊皮款易划痕，成色扣分大", "链条脱色、内衬粘皮是常见扣价项", "同款色号不同年份差价可达 20%"]
  },
  lv: {
    intro: "涂层帆布老花耐磨抗造，流通量全网第一，是最好出货的品类。但近期受商标维权风波影响，部分热门款二手价格波动加大，回收口径明显收紧。",
    rules: [
      "Date Code（如 FL0156）标注产地与年份，是估价硬指标",
      "2021 年后部分新款内置 NFC 芯片",
      "老花帆布 > 皮具款；老花经典通勤款流通最快，非老花皮具款折价极狠",
      "植鞣革提手易变色（蜜蜡化属正常），重度变色扣价明显"
    ],
    risks: ["Carryall 等近期爆款波动剧烈，切勿高位收", "老花肩带边缘磨损是高频问题", "冷门皮具款二手几乎无人接"]
  },
  dior: {
    intro: "唯一同时拥有高级定制、成衣、皮具、香化、珠宝全品类的时装屋。Lady Dior 与 Saddle 马鞍包为标志产品，辨识度高但材质娇贵，成色是估价分水岭。",
    rules: [
      "序列号首两位为产地代码：01 = 意大利，04 = 法国",
      "2020 年起启用带二维码 + 12 位编码的新版身份卡；部分新款内置 NFC",
      "藤格纹（Cannage）对称度、D-I-O-R 吊坠重量与镀层是核心鉴定点",
      "羊皮款成色折损远大于帆布款（Book Tote）"
    ],
    risks: ["Lady Dior 羊皮款划痕直接掉一档", "戴妃包配色冷门（如荧光色）流通慢", "高仿集中，必须验字体烫印"]
  },
  rolex: {
    intro: "硬奢代表。2022 年见顶后持续回调，WatchCharts 显示二手均价两年跌约 11.5%。但水鬼、迪通拿等经典运动款流通性依然最强，空霸/恒动等贴近公价款回调中近乎免疫。",
    rules: [
      "回收价约为公价 4~8 折，热门运动款贴上沿，正装款贴下沿",
      "带有效在保保卡可溢价 10%~15%；缺保卡折价 12%~25%；全套齐全溢价 8%~22%",
      "绿水鬼全套比裸表高 5000~20000 元",
      "卖表前不要自行打磨抛光，多次深度抛光会削减表壳厚度，直接影响估值"
    ],
    risks: ["绿金迪等全金款从峰值大幅回落，切勿按旧行情报价", "间金日志折价 28%~33%，全金日志超 30%", "Pearlmaster、Sky-Dweller 非核心系列下滑明显"]
  },
  omega: {
    intro: "二手性价比路线，流通量稳定。运动款（超霸/海马）保值明显好于正装款（蝶飞），是入门玩家的主力选择。",
    rules: ["超霸系列保值率普遍 > 70%", "海马系列 55%~70%，海马 300 米流通最快", "蝶飞系列仅 45%~55%，流通周期长"],
    risks: ["正装款折价明显", "同型号不同机芯代际（如海马 8800 前后）价差大"]
  },
  cartier: {
    intro: "轻奢女士腕表标杆，蓝气球、坦克、山度士三大系列常年流通活跃。坦克小号钢款保值率可达 93%~96%，是品牌内表现最好的款式。",
    rules: ["蓝气球 33mm 间金机械款回收约公价 55%~65%", "42mm 钢款约 50%", "满钻款不足 25%，不建议作为保值标的"],
    risks: ["满钻款折价极深", "蓝气球高仿泛滥，必须核对机芯与刻印"]
  },
  vca: {
    intro: "四叶草（Alhambra）是二手高珠的硬通货，流通速度快。材质保值梯度经市场验证：红玉髓 > 黑玛瑙 > 白贝母 > 孔雀石。",
    rules: [
      "正品每朵四叶草边缘有 10 颗浑圆立体小金珠，大小一致、排列紧密",
      "五花手链（红玉髓/黑玛瑙）是公认保值王者，95 新全套回收可达 3.5~3.8 万",
      "白贝母遇水易发黄，二手价格低 5%~10%；孔雀石硬度低易磕碰，折扣最大",
      "全套附件比裸件溢价 5%~20%"
    ],
    risks: ["孔雀石几乎是折价重灾区", "带钻款碎钻不保值，仅主钻 0.5ct 以上有回收价值", "二三线城市回收渠道少，压价空间大"]
  },
  cartier_j: {
    intro: "LOVE、钉子、Trinity 三大经典系列的素金无钻款是二手市场公认硬通货，95 新全套回收率约 70%~88%。玫瑰金行情优于白金与黄金。",
    rules: [
      "无钻宽版手镯保值率最高，回收价可达原价 85% 左右",
      "窄版无钻 18K 玫瑰金全套回收约 1.25 万~1.6 万",
      "满钻手镯回收 57%~65%；带钻戒指最低，仅 30%~38%",
      "刻印字体、间距、深浅需用宝石显微镜核验，是鉴定核心"
    ],
    risks: ["带钻戒指折价最狠，不建议收", "非全套附件直接减 5%~20%", "18K 金价波动会带动基础材质价值变化"]
  },
  bvlgari: {
    intro: "B.zero1 与 Serpenti 灵蛇为两大支柱。整体回收价区间在 20%~45%，经典款较坚挺，季节限定款贬值幅度大。",
    rules: ["B.zero1 系列回收约专柜价 50%~68%", "黑陶瓷三环弹簧手镯流通性最稳", "Serpenti 满钻款保值率可达 65%~75%"],
    risks: ["彩色宝石镶嵌款、季节限定款贬值大", "单圈无钻细款回收价可能仅 5000~7000 元"]
  },
  tiffany: {
    intro: "T 系列 18K 金素金款是品牌内保值最好的品类，回收稳定在公价 55%~70%，流通速度极快。但银饰是折价重灾区。",
    rules: ["T 系列素金 55%~70%", "Setting 六爪钻戒有 GIA 证书才保值，约 44%~56%", "银饰（Return to Tiffany 等）仅剩原价 20%~30%"],
    risks: ["银饰几乎无回收价值", "等级划分混乱，同款不同代差价大", "无 GIA 证书钻饰缩水 20%~30%"]
  },
  patek: {
    intro: "冰火两重天。运动钢款（鹦鹉螺 5711）停产稀缺，保值率超 200%；正装金款（卡拉卓华）折价率超 40%，流通缓慢。",
    rules: ["Nautilus 近半年涨约 4.3%，Aquanaut 约 6.8%，Calatrava 跌约 3.1%", "鹦鹉螺 5711/1A 停产，95 新全套 76 万~85 万，处企稳区间"],
    risks: ["正装金款流动性极差", "配件（原厂表扣、保卡）缺失严重贬值"]
  },
  ap: {
    intro: "皇家橡树是抗跌性最强的系列之一，15500ST 蓝面款全年涨约 4.5%，稳定在 20 万以上。离岸型折价明显。",
    rules: ["15500ST 钢款蓝盘回收 23 万~28 万，保值率 105%~127%", "离岸型折价 20%~40%"],
    risks: ["离岸型非热门配色流通慢", "表壳棱角抛光损耗直接影响估值"]
  },
  gucci: {
    intro: "流量品牌，老花系列性价比稳定，但整体保值弱于 LV。1955 马衔扣与 Jackie1961 为近年主力款。",
    rules: ["1955 马衔扣中号公价约 2.3 万，95 新全套回收 1.0 万~1.2 万", "Jackie1961 小号老花回收 6000~8000 元"],
    risks: ["帆布老花材质不耐磨，边角磨损直接拉低报价", "季节性设计款流通极慢"]
  },
  longines: {
    intro: "中端入门首选，康卡斯与名匠流通量大，回收价多集中在公价 3~5 折。",
    rules: ["康卡斯潜水（公价约 1.5 万）回收 0.6 万~0.8 万", "名匠系列（公价约 2 万）回收 0.8 万~1.0 万"],
    risks: ["单表无保卡折价大", "年款更新快，老款掉价明显"]
  },
  tudor: {
    intro: "劳力士兄弟品牌，碧湾系列性价比突出，二手市场表现稳健。",
    rules: ["碧湾 1958（公价约 3 万）回收 1.8 万~2.2 万", "自产 MT5402 机芯加持，市场认可度高"],
    risks: ["非碧湾系列流通性一般"]
  }
};

/* ---------- 产品库 ---------- */
/* price: 专柜公价(元) ; low/high: 95新全套回收参考区间 ; trend: 近90天涨跌% ; ret: 保值率% */
const PRODUCTS = [
  /* ===== 爱马仕 ===== */
  { id:"h1", img:"img/h1.jpg", brand:"hermes", cat:"包袋", series:"Birkin", name:"Birkin 25 金刚色", spec:"Togo 皮 · 黑金/金棕/大象灰",
    price:115000, low:120000, high:160000, trend:3, ret:130, heat:98,
    tags:["硬通货","金刚色","流通最快"],
    desc:"顶奢硬通货，转手周期通常不超过一周。金刚色 + 25cm 尺寸是溢价最猛的组合，95 新全套常超公价。",
    points:["稀缺皮质与金刚色是核心护城河","全套附件（盒/防尘袋/锁匙/雨衣/票）溢价 10%~20%","配货比金刚色新客可达 1:1.5~1:2"],
    risk:"配货成本高，非本行客源慎入；成色判断误差直接影响数万元。",
    advice:"卖方市场，可坚定报价；有金刚色现货建议快进快出。"},
  { id:"h2", img:"img/h2.jpg", brand:"hermes", cat:"包袋", series:"Kelly", name:"Kelly 28 金棕", spec:"Epsom 皮 · 金扣",
    price:92000, low:105000, high:135000, trend:2, ret:125, heat:95,
    tags:["经典尺寸","金棕"],
    desc:"单手柄 + 肩带，兼具优雅与实用。Kelly 的溢价率与流通速度略低于 Birkin，但依然是最稳的顶奢资产。",
    points:["外缝/内缝价格差约 5%","金棕配色二手流通速度极快","Epsom 皮硬挺不易变形，成色易维持"],
    risk:"Epsom 皮修复难度大，边角磨损扣价明显。",
    advice:"金棕 + 28cm 是安全牌；非全套附件按 8~9 折报价。"},
  { id:"h3", brand:"hermes", cat:"包袋", series:"Kelly", name:"Mini Kelly 二代", spec:"Swift 皮 · 任意配色",
    price:65000, low:120000, high:150000, trend:5, ret:150, heat:96,
    tags:["超溢价","流通性极强"],
    desc:"迷你尺寸近年热度持续走高，二级市场成交价甚至远超原价，是目前溢价倍率最高的款式之一。",
    points:["迷你尺寸流通性极强","溢价率可达公价 180%~230%","Swift 皮柔软，成色保持是关键"],
    risk:"价格已处高位，行情回调风险大，切忌追高收货。",
    advice:"有货可接，但必须留足安全垫；高位行情不宜长期持有。"},
  { id:"h4", img:"img/h4.jpg", brand:"hermes", cat:"包袋", series:"Constance", name:"Constance 19", spec:"常规皮 · 金刚色",
    price:78000, low:88000, high:115000, trend:1, ret:118, heat:90,
    tags:["H扣","产量极少"],
    desc:"H 扣设计辨识度极高，产量极少导致购买难度大，二手同样紧俏。近年涨幅略高于 Birkin。",
    points:["小巧精致，肩带可拆","金刚色流通稳定","全套溢价明显"],
    risk:"不适合作为入门第一只爱马仕；翻新件鉴别难度较高。",
    advice:"验包重点看 H 扣镀层与内里烫印。"},
  { id:"h5", img:"img/h5.jpg", brand:"hermes", cat:"包袋", series:"Picotin Lock", name:"Picotin 18 菜篮子", spec:"清朗皮 · 金刚色",
    price:30000, low:28000, high:35000, trend:0, ret:98, heat:82,
    tags:["低配货","入门首选"],
    desc:"入门级硬通货，通常无需配货，是建立消费记录的最佳跳板，二手流通量稳定。",
    points:["无需配货或仅需少量消费记录","金刚色溢价略高","皮料软，形状保持是估价要点"],
    risk:"包身易塌，变形后扣价明显。",
    advice:"适合走量，适合作为新手客户的入门推荐。"},
  { id:"h6", brand:"hermes", cat:"包袋", series:"Lindy", name:"Lindy 26", spec:"清朗皮 · 金刚色",
    price:45000, low:75000, high:90000, trend:1, ret:110, heat:80,
    tags:["入门硬通货","通勤"],
    desc:"Lindy 是入门级里保值表现最好的款式，金刚色流通稳定，容量大受通勤客欢迎。",
    points:["无硬性配货要求","金刚色最好出货","自重约 1.2kg，肩背压肩"],
    risk:"包型软，边角磨损扣价较大。",
    advice:"适合稳健盘，不宜压价过猛以免丧失货源。"},

  /* ===== 香奈儿 ===== */
  { id:"c1", img:"img/c1.jpg", brand:"chanel", cat:"包袋", series:"Classic Flap", name:"CF 中号 黑金", spec:"鱼子酱皮 Caviar · 25cm",
    price:88000, low:52000, high:68000, trend:-2, ret:82, heat:97,
    tags:["定海神针","流通最快"],
    desc:"市场的定海神针。95 新回收价稳定在公价 55%~75%，黑金款二手保值率可达 90%~110%，流通速度以天计算。",
    points:["黑金款三年增值约 37%","鱼子酱皮耐磨，成色保持好","同尺寸 CF 专柜价比 2.55 贵约 3000~5000 元"],
    risk:"每年两轮调价，但二手端涨幅未完全跟进，存在价格倒挂风险。",
    advice:"最稳的收货标的；内衬粘皮、链条脱色是两大扣价点。"},
  { id:"c2", img:"img/c2.jpg", brand:"chanel", cat:"包袋", series:"2.55 Reissue", name:"2.55 小号", spec:"做旧小牛皮 · 黑银/黑金",
    price:80000, low:48000, high:55000, trend:-1, ret:78, heat:88,
    tags:["常青款","低调"],
    desc:"原创翻盖设计，收藏价值受认可。黑银做旧牛皮款回收价通常维持在公价 70%~80%。",
    points:["复古感强，资深玩家偏好","银扣氧化比金扣明显，成色好溢价空间大","受众广泛，常年不愁流通"],
    risk:"银扣氧化是高频扣价项，需如实评估。",
    advice:"银扣款验货必查氧化程度，直接拍照记录。"},
  { id:"c3", img:"img/c3.jpg", brand:"chanel", cat:"包袋", series:"22 Bag", name:"22 Bag 中号", spec:"羊皮 · 黑色",
    price:50000, low:28000, high:32000, trend:-6, ret:62, heat:84,
    tags:["近年热门","流通较快"],
    desc:"近年热度快速上升的款式，黑色经典配色流通较快，但羊皮材质与流行周期决定了其保值不如 CF。",
    points:["造型时髦，年轻客群接受度高","黑色最稳，其他配色折价明显"],
    risk:"羊皮易划伤；流行周期过后可能快速降温，不宜长期持有。",
    advice:"快进快出策略，不要压资金。"},
  { id:"c4", brand:"chanel", cat:"包袋", series:"Le Boy", name:"Le Boy 中号 黑金", spec:"小羊皮/鱼子酱皮",
    price:62000, low:22000, high:32000, trend:-5, ret:58, heat:76,
    tags:["经典但降温"],
    desc:"曾经的现象级款式，近年来热度被 22 Bag 与 19Bag 分流，二手价格回落明显。",
    points:["黑金配色仍是最好出手的组合","鱼子酱皮版本比羊皮版本抗跌"],
    risk:"整体热度下行，收货宜压价。",
    advice:"只收黑金 + 鱼子酱皮，其他配置谨慎。"},

  /* ===== LV ===== */
  { id:"l1", brand:"lv", cat:"包袋", series:"Carryall", name:"Carryall 小号 老花", spec:"Monogram 涂层帆布",
    price:21000, low:11000, high:14000, trend:-12, ret:65, heat:90,
    tags:["近期爆款","波动大"],
    desc:"近年流量爆款，入门首选。但受商标维权风波与供给放量影响，二手价波动剧烈，需警惕高位持仓。",
    points:["包型实用，二手需求旺盛","植鞣革提手易变色，影响估价","回收率约 45%~62%"],
    risk:"价格波动大，行情下行期收货需大幅预留空间。",
    advice:"近期报价从紧，建议先确认下游出货渠道再接单。"},
  { id:"l2", img:"img/l2.jpg", brand:"lv", cat:"包袋", series:"Neverfull", name:"Neverfull 中号 老花", spec:"Monogram 涂层帆布",
    price:15000, low:8000, high:12000, trend:1, ret:88, heat:95,
    tags:["万年经典","几乎不贬值"],
    desc:"万年经典托特，市场存量大、受众广。九成新附件齐全款保值率约 88%，因专柜多次调价，二手行情还在稳步回升。",
    points:["流通最快，出手无压力","日常置换频次高，走量首选","内袋污渍、肩带磨损是主要扣价点"],
    risk:"存量极大，单件利润薄，靠周转赚钱。",
    advice:"薄利多销，重点做周转效率。"},
  { id:"l3", img:"img/l3.jpg", brand:"lv", cat:"包袋", series:"Speedy", name:"Speedy B25 老花", spec:"Monogram 涂层帆布",
    price:17800, low:9000, high:12000, trend:0, ret:72, heat:88,
    tags:["经典","通勤"],
    desc:"经典桶型，轻便实用，是许多人第一只大牌包的默认选项，二手需求稳定。",
    points:["轻便抗造，日常使用频次高","老花帆布防水防刮","肩带边缘易磨损需检查"],
    risk:"植鞣革配件变色后扣价，需如实定价。",
    advice:"稳妥走量款，报错空间小。"},
  { id:"l4", img:"img/l4.jpg", brand:"lv", cat:"包袋", series:"Onthego", name:"Onthego 中号", spec:"Monogram Giant 帆布",
    price:24500, low:9000, high:12000, trend:-7, ret:55, heat:72,
    tags:["大包潮流"],
    desc:"大容量托特，曾经热门，随着大包潮流降温，二手流通速度放缓。",
    points:["容量极大，商旅客群需求","Monogram Giant 印花辨识度高"],
    risk:"体积大、运费与仓储成本高，周转慢。",
    advice:"谨慎收货，优先接已确认的订单再进货。"},

  /* ===== 迪奥 ===== */
  { id:"d1", img:"img/d1.jpg", brand:"dior", cat:"包袋", series:"Lady Dior", name:"Lady Dior 三格", spec:"黑色羊皮 · 藤格纹",
    price:46000, low:13000, high:20000, trend:-6, ret:48, heat:88,
    tags:["戴妃包","常青款"],
    desc:"戴妃包常青款，名媛风格辨识度极高。但羊皮娇贵，成色是价格分水岭。",
    points:["藤格纹对称度、D-I-O-R 吊坠是核心鉴定点","序列号首两位 01=意大利 / 04=法国","保存良好的可往高价靠"],
    risk:"羊皮划痕、边角磨损对价格影响极大，收货务必细看。",
    advice:"带手套验包，瑕疵逐项拍照留证；羊皮成色差的直接压价。"},
  { id:"d2", img:"img/d2.jpg", brand:"dior", cat:"包袋", series:"Saddle", name:"Saddle 马鞍包", spec:"老花帆布",
    price:29000, low:14000, high:19000, trend:2, ret:58, heat:80,
    tags:["复古回潮"],
    desc:"复古回潮人气款，流通较快，帆布材质比羊皮版本更容易维持成色。",
    points:["2021 年复刻版内置 NFC 芯片","帆布款耐造，成色保持好","马鞍造型辨识度高"],
    risk:"肩带为易损件，缺失或后配会明显折价。",
    advice:"重点核查肩带与原装包装。"},
  { id:"d3", brand:"dior", cat:"包袋", series:"Book Tote", name:"Book Tote 中号", spec:"老花刺绣 · 帆布",
    price:26000, low:18000, high:26000, trend:0, ret:62, heat:74,
    tags:["入门款","大容量"],
    desc:"从 1.8 万起的老花帆布托特是 Dior 的入门门面，容量实用，二手流通中等。",
    points:["帆布材质耐造，成色好维持","刺绣版本溢价高于纯色版本"],
    risk:"尺寸偏大，仓储与运输成本高。",
    advice:"适合作引流款，利润空间有限。"},

  /* ===== 劳力士 ===== */
  { id:"r1", img:"img/r1.jpg", brand:"rolex", cat:"腕表", series:"Submariner", name:"绿水鬼 126610LV", spec:"41mm 精钢 · 自动",
    price:108000, low:82000, high:100000, trend:-8, ret:80, heat:92,
    tags:["溢价收窄","回流钢款"],
    desc:"溢价已收窄至 0%~6%，正在回归消费品属性。较 2022 年 18 万峰值跌去约 42%。",
    points:["全套完整溢价 8%~22%","带在保保卡可再溢价 10%~15%","流通速度快，不缺买家"],
    risk:"仍处下行通道，切勿按峰值行情报价。",
    advice:"按当日行情实时报价，不做长周期持仓。"},
  { id:"r2", brand:"rolex", cat:"腕表", series:"Submariner", name:"黑水鬼 126610LN 有历", spec:"41mm 精钢 · 自动",
    price:91000, low:78000, high:95000, trend:-4, ret:92, heat:96,
    tags:["硬通货","流通最快"],
    desc:"接近公价，是流通最快的入门钢款之一。哪怕最保值的款，回收价与零售价之间也天然隔着一截。",
    points:["Rolex 回收价通常为公价 4~8 折，此款贴上沿","全套比裸表明显更高","空霸/恒动类贴近公价款回调中近乎免疫"],
    risk:"单表裸出折价大，必须确认保卡。",
    advice:"最容易周转的标的，适合作为资金池主力。"},
  { id:"r3", img:"img/r3.jpg", brand:"rolex", cat:"腕表", series:"Daytona", name:"熊猫迪 116500LN", alias:"panda 迪通拿 白熊猫", spec:"40mm 精钢 · 自动计时",
    price:115000, low:180000, high:220000, trend:-9, ret:135, heat:97,
    tags:["钢王","溢价超公价"],
    desc:"热度仍在，回收价反超公价约 60%。较峰值 40 万近乎腰斩，但仍是二级市场最坚挺的钢款之一。",
    points:["全套附件齐全的 95 新成交可达 20~22 万","白盘熊猫盘溢价最高","流通性强，出手快"],
    risk:"高位标的价格回调风险大，一枚表的资金占用高。",
    advice:"大额标的，务必双方复核机芯与保卡后再成交。"},
  { id:"r4", brand:"rolex", cat:"腕表", series:"Daytona", name:"绿金迪 116508", alias:"迪通拿 绿金", spec:"40mm 黄金 · 自动计时",
    price:0, low:400000, high:430000, trend:-15, ret:60, heat:70,
    tags:["高位回落","全金款"],
    desc:"较巅峰期（曾超 120 万）回落明显。全金表款在行情下行期承压最重。",
    points:["黄金材质本身有金价支撑","全金款折价率突破 30%"],
    risk:"极高资金占用 + 持续贬值，是当前最不适合囤货的品类之一。",
    advice:"仅接已确定的下游订单，不主动囤货。"},
  { id:"r5", brand:"rolex", cat:"腕表", series:"Datejust", name:"日志型 126334 蓝盘", spec:"41mm 间金 · 自动",
    price:80000, low:42000, high:58000, trend:-10, ret:62, heat:68,
    tags:["正装款","折价明显"],
    desc:"正装款折价相对明显，间金日志折价 28%~33%。受众偏成熟消费群体。",
    points:["蓝盘是日志系列较好出手的配色","包装与保卡齐全非常重要"],
    risk:"正装款在下行行情中流动性差，变现慢。",
    advice:"收货务必保守，做好长周转准备。"},

  /* ===== 百达翡丽 / 爱彼 / 欧米茄 / 卡地亚 ===== */
  { id:"p1", img:"img/p1.jpg", brand:"patek", cat:"腕表", series:"Nautilus", name:"鹦鹉螺 5711/1A 蓝盘", spec:"40mm 精钢 · 已停产",
    price:0, low:760000, high:850000, trend:4, ret:210, heat:90,
    tags:["停产稀缺","硬通货"],
    desc:"已停产稀缺款，硬通货处于企稳区间。保值率超过 200%，是二级市场金字塔顶端。",
    points:["Nautilus 系列近半年上涨约 4.3%","停产带来不可逆稀缺性","原厂表扣、保卡缺失严重贬值"],
    risk:"单笔资金占用极大，鉴定门槛高，需专业渠道配合。",
    advice:"建议联合鉴定机构与资金方共同操作，不做独立接单。"},
  { id:"p2", brand:"ap", cat:"腕表", series:"Royal Oak", name:"皇家橡树 15500ST 蓝盘", spec:"41mm 精钢 · 自动",
    price:241000, low:230000, high:280000, trend:4, ret:110, heat:85,
    tags:["抗跌","蓝盘最稳"],
    desc:"高于专柜公价，流通性强。全年涨幅约 4.5%，是当前二级市场中抗跌性较强的系列。",
    points:["15500ST 保值率 105%~127%","蓝盘是系列内最稳配色","八角形表圈棱角抛光损耗直接影响估值"],
    risk:"离岸型折价 20%~40%，不要与皇家橡树混淆定价。",
    advice:"验收重点：表壳棱角是否原厂、有无二次抛光。"},
  { id:"o1", brand:"omega", cat:"腕表", series:"Seamaster", name:"海马 300 米 钢款", spec:"42mm 精钢 · 8800 机芯",
    price:48000, low:32000, high:38000, trend:-6, ret:68, heat:88,
    tags:["通勤热门","流通快"],
    desc:"通勤热门款，需求稳定。搭载 8800 机芯的第四代（2018 年至今）黑/蓝盘钢带款流通性最强。",
    points:["95 新全套 3.2 万~3.8 万","保值率 55%~70%","二手性价比突出，入门客群主力"],
    risk:"蝶飞等正装款保值仅 45%~55%，不要混为一谈。",
    advice:"第四代 8800 机芯款可放心接，老机芯款压价。"},
  { id:"o2", brand:"omega", cat:"腕表", series:"Speedmaster", name:"超霸 月球表", spec:"42mm 精钢 · 手动计时",
    price:52000, low:38000, high:43000, trend:-3, ret:72, heat:80,
    tags:["历史加持","保值率最高"],
    desc:"登月历史加持，手动计时的经典之作，是欧米茄内保值表现最好的系列。",
    points:["超霸系列保值率普遍 > 70%","原装表带、盒证齐全溢价明显"],
    risk:"手动款受众相对窄，周转略慢于海马。",
    advice:"适合做品类补充，不建议作为主力。"},
  { id:"ct1", brand:"cartier", cat:"腕表", series:"Ballon Bleu", name:"蓝气球 33mm 间金机械", spec:"33mm · 间金 · 自动",
    price:0, low:36000, high:48000, trend:2, ret:62, heat:86,
    tags:["女士标杆","流通快"],
    desc:"卡地亚女士腕表标杆，33mm 间金机械款回收约公价 55%~65%，流通速度快。",
    points:["受众覆盖女性通勤、婚嫁、商务人群","蓝气球 42mm 钢款回收约 50%","满钻款不足 25%"],
    risk:"高仿泛滥，机芯与刻印必须双重核验。",
    advice:"女士款客群稳定，适合门店常备 1~2 只。"},
  { id:"ct2", brand:"cartier", cat:"腕表", series:"Santos", name:"山度士 中号", spec:"35mm 精钢 · 自动",
    price:45000, low:25000, high:30000, trend:1, ret:60, heat:70,
    tags:["方壳复古"],
    desc:"方壳复古风格，表带快拆系统便于更换，二手流通中等。",
    points:["钢款保值约 60%","快拆表带降低维护成本"],
    risk:"方壳表耳磨损影响观感，成色评估偏严。",
    advice:"适合搭配蓝气球一起做女士腕表盘。"},

  /* ===== 首饰 ===== */
  { id:"v1", img:"img/v1.jpg", brand:"vca", cat:"首饰", series:"Alhambra", name:"四叶草五花手链 红玉髓", spec:"18K 黄金 · 中号",
    price:42000, low:35000, high:38000, trend:2, ret:82, heat:92,
    tags:["保值王者","常年缺货"],
    desc:"公认的保值王者，95 新全套可达 3.5 万~3.8 万，保值率超过 80%，二手市场常年处于缺货状态。",
    points:["正品每朵四叶草边缘有 10 颗浑圆小金珠，排列紧密","红玉髓 > 黑玛瑙 > 白贝母 > 孔雀石","全套附件比裸件溢价 5%~20%"],
    risk:"高仿密集，必须放大镜核验金珠排列与刻印字体。",
    advice:"首饰类里最值得囤的标的，红玉髓/黑玛瑙优先。"},
  { id:"v2", brand:"vca", cat:"首饰", series:"Alhambra", name:"四叶草中号单花项链 红玉髓", spec:"18K 黄金 · 中号",
    price:20000, low:16000, high:18000, trend:1, ret:80, heat:90,
    tags:["抗跌"],
    desc:"红玉髓款最抗跌，95 新全套中号单花项链回收约 1.6 万~1.8 万，保值率 75%~85%。",
    points:["颜色饱和度高、易佩戴、不易磨损","无钻款流通优于带钻款"],
    risk:"白贝母款遇水易发黄，二手价格低 5%~10%。",
    advice:"只收红玉髓/黑玛瑙，白贝母款慎重。"},
  { id:"v3", brand:"vca", cat:"首饰", series:"Alhambra", name:"四叶草手链 孔雀石款", spec:"18K 黄金 · 五花",
    price:42000, low:36000, high:38000, trend:0, ret:55, heat:65,
    tags:["折价重灾区"],
    desc:"孔雀石硬度仅 3.5~4，轻微磕碰即留痕，回收商压价最狠，是四叶草系列中折价最大的材质。",
    points:["颜色受年轻客群喜爱","但材质耐久性最差"],
    risk:"极易留痕，成色扣分严重，二三线城市回收渠道少。",
    advice:"不建议囤货，仅接受客户订单后接货。"},
  { id:"cj1", img:"img/cj1.jpg", brand:"cartier_j", cat:"首饰", series:"LOVE", name:"LOVE 无钻宽版手镯", spec:"18K 玫瑰金 · 宽版",
    price:58000, low:42000, high:50000, trend:3, ret:85, heat:95,
    tags:["硬通货","素金最保值"],
    desc:"Love 系列中保值率最高的单品，回收价可达原价 85% 左右。玫瑰金行情优于白金与黄金。",
    points:["无钻宽版是硬通货，95 新全套回收率 70%~88%","按材质 + 品牌溢价 + 工艺 + 附件分项计价","18K 金价波动影响材质基础价值"],
    risk:"带钻戒指折价最狠，仅 30%~38%，不要与手镯同价处理。",
    advice:"分项报价（金料价值 + 品牌溢价 + 工艺 + 附件），客户接受度最高。"},
  { id:"cj2", brand:"cartier_j", cat:"首饰", series:"LOVE", name:"LOVE 无钻窄版手镯", spec:"18K 玫瑰金 · 窄版",
    price:38000, low:12500, high:16000, trend:1, ret:72, heat:86,
    tags:["入门款","走量"],
    desc:"18K 玫瑰金窄版无钻手镯全套回收价约 1.25 万~1.6 万，是二手首饰里的走量款。",
    points:["入手门槛低，成交频次高","玫瑰金好出手"],
    risk:"克重小，金价波动对基础价值影响占比高。",
    advice:"走量款，重点算清当日金价与克重。"},
  { id:"cj3", brand:"cartier_j", cat:"首饰", series:"LOVE", name:"LOVE 满天星满钻手镯", spec:"18K 玫瑰金 · 满钻",
    price:280000, low:160000, high:200000, trend:-3, ret:62, heat:78,
    tags:["钻石加持"],
    desc:"满钻手镯回收价在 57%~71% 之间，钻石加持带来溢价，但回收价约 16 万~20 万，折价率仍不低。",
    points:["钻石品质需单独分级评估","有 GIA 同等级证书可提升价值锚点"],
    risk:"碎钻保值能力弱，非主钻类回收折价明显。",
    advice:"必须要求钻石分级依据，按品质单独议价。"},
  { id:"b1", brand:"bvlgari", cat:"首饰", series:"B.zero1", name:"B.zero1 黑陶瓷三环弹簧手镯", spec:"18K 金 + 陶瓷",
    price:0, low:15000, high:25000, trend:-2, ret:60, heat:80,
    tags:["流通稳定"],
    desc:"B.zero1 系列整体回收约专柜价 50%~68%，黑陶瓷三环弹簧手镯流通性最稳定。",
    points:["造型辨识度高，年轻客群偏好","陶瓷部分不易磨损"],
    risk:"彩色宝石镶嵌款与季节限定款贬值幅度大。",
    advice:"只做经典黑陶瓷款，限定款谨慎。"},
  { id:"b2", brand:"bvlgari", cat:"首饰", series:"Serpenti", name:"Serpenti 灵蛇满钻戒指", spec:"18K 金 · 满钻",
    price:55000, low:28000, high:35000, trend:-1, ret:62, heat:72,
    tags:["蛇头辨识度高"],
    desc:"Serpenti 满钻款保值率可达 65%~75%，蛇头设计辨识度高，是宝格丽内较坚挺的类别。",
    points:["满钻款优于素金细款","蛇头工艺是鉴定核心"],
    risk:"单圈无钻细款回收价可能仅 5000~7000 元，切勿混淆。",
    advice:"按款型分档报价，避免客户预期错位。"},
  { id:"t1", brand:"tiffany", cat:"首饰", series:"T", name:"T 系列微笑项链", spec:"18K 金 · 无钻",
    price:21000, low:10500, high:12000, trend:-4, ret:52, heat:84,
    tags:["流通极快"],
    desc:"T 系列 18K 金素金款是蒂芙尼保值率最高的品类，回收稳定在专柜公价 55%~70%，流通速度极快。",
    points:["Smile 无钻项链 95 新全套回收约 1.05 万","素金款抗跌，流通快"],
    risk:"银饰（Return to Tiffany 等）仅剩原价 20%~30%，是折价重灾区。",
    advice:"只收 18K 金款，银饰基本不接。"},
  { id:"t2", brand:"tiffany", cat:"首饰", series:"Setting", name:"六爪钻戒 1 克拉", spec:"铂金/18K · GIA 证书",
    price:80000, low:35000, high:45000, trend:-3, ret:50, heat:70,
    tags:["看证书"],
    desc:"附带 GIA 证书为硬指标，回收约 44%~56%；无证书同款式回收价缩水 20%~30%。",
    points:["钻石按 4C 独立分级评估","持 GIA 证书的钻石部分回收价可上浮 20%~30%"],
    risk:"无证书直接缩水，且裸钻级产品市场波动大。",
    advice:"没有 GIA 证书的报价直接下调 20% 起。"},

  /* ===== 古驰 ===== */
  { id:"g1", img:"img/g1.jpg", brand:"gucci", cat:"包袋", series:"1955", name:"1955 马衔扣 中号", spec:"帆布老花 · 肩背",
    price:23000, low:10000, high:12000, trend:-5, ret:52, heat:76,
    tags:["复古风"],
    desc:"复古风潮带火了这款，但帆布老花材质不耐磨，边角磨损会直接拉低报价。",
    points:["马衔扣设计经典","公价 2.3 万，95 新全套回收约 1.0 万~1.2 万"],
    risk:"边角磨损扣价重，收前必查四角。",
    advice:"保守收货，利润空间有限。"},
  { id:"g2", img:"img/g2.jpg", brand:"gucci", cat:"包袋", series:"Jackie 1961", name:"Jackie 1961 小号 老花", spec:"帆布老花",
    price:20000, low:6000, high:8000, trend:-4, ret:40, heat:66,
    tags:["小众受众"],
    desc:"马衔扣设计，有固定受众但流通面窄，回收价 6000~8000 元。",
    points:["造型复古，有特定客群"],
    risk:"整体保值率低于 LV 同价位款，变现慢。",
    advice:"只接已确认的下游订单。"},

  /* ===== 帝舵 / 浪琴 ===== */
  { id:"td1", brand:"tudor", cat:"腕表", series:"Black Bay", name:"碧湾 1958", spec:"39mm 精钢 · MT5402 机芯",
    price:30000, low:18000, high:22000, trend:0, ret:68, heat:74,
    tags:["性价比"],
    desc:"复古潜水风，机芯自产 MT5402，二手市场表现稳健，是劳力士兄弟品牌的主力流通款。",
    points:["自产机芯加持，市场认可度高","公价约 3 万，回收 1.8 万~2.2 万"],
    risk:"非碧湾系列流通性一般。",
    advice:"入门腕表客群的主力，适合走量。"},
  { id:"lg1", brand:"longines", cat:"腕表", series:"Conquest", name:"康卡斯 潜水", spec:"41mm 精钢 · 自动",
    price:15000, low:6000, high:8000, trend:-6, ret:45, heat:70,
    tags:["入门潜水"],
    desc:"入门潜水表，性价比之选，回收价多集中在公价 3~5 折。",
    points:["门槛低，成交频次高","无保卡折价大"],
    risk:"年款更新快，老款掉价明显。",
    advice:"做引流品类，不指望利润。"},

  /* ===== 2026-10 扩充 · 包袋 ===== */
  { id:"n1", brand:"hermes", cat:"包袋", series:"Birkin", name:"Birkin 30 黑金刚色", spec:"Togo 皮 · 黑金",
    price:105000, low:78000, high:125000, trend:2, ret:97, heat:92,
    tags:["硬通货","通勤尺寸"],
    desc:"30cm 是 Birkin 流通量最大的尺寸，通勤与场合兼顾。黑金全套稳定在公价附近或以上。",
    points:["流通最快的大尺寸","全套附件溢价 10%~18%","金刚色之外的冷门色折价 15%~25%"],
    risk:"手柄底部磨损、锁匙缺失是高频扣价项。",
    advice:"收包首选尺寸，转手周期 1~3 周。"},
  { id:"n2", brand:"hermes", cat:"包袋", series:"Birkin", name:"Birkin 35 金棕色", spec:"Togo 皮 · 金扣",
    price:92000, low:58000, high:82000, ret:76, heat:72, trend:-3,
    tags:["大尺寸","折价明显"],
    desc:"35/40 大尺寸受众窄，2026 年行情回落到公价 65%~75%，急售需打八折。",
    points:["金棕是最抗跌的大尺寸配色","适合预算型买家"],
    risk:"转手周期长，库存占资金。",
    advice:"低价收、慢周转，报价留足安全垫。"},
  { id:"n3", brand:"hermes", cat:"包袋", series:"Kelly", name:"Kelly 25 黑金", spec:"Epsom 皮 · 金扣",
    price:86000, low:130000, high:170000, trend:4, ret:175, heat:94,
    tags:["硬通货","超公价"],
    desc:"Kelly 25 是仅次于 Birkin 25 的溢价王，黑金全套 95 新稳定超公价 50% 以上。",
    points:["外缝款更受欢迎","稀有配色（奶昔白/三文鱼粉）再上浮 20%~40%"],
    risk:"内缝/外缝混淆估价会出错，需看清。",
    advice:"卖方市场，坚定报价；收货核对年份刻印。"},
  { id:"n4", brand:"hermes", cat:"包袋", series:"Evelyne", name:"Evelyne 16 斜挎", spec:"Epsom 皮 · 黑/大象灰",
    price:21000, low:9000, high:13500, ret:54, heat:68, trend:-2,
    tags:["入门款","斜挎"],
    desc:"爱马仕门槛最低的斜挎款之一，年轻人入场款，流通稳定但无溢价。",
    points:["打孔 H 标识款更受欢迎","适合配货凑单"],
    risk:"穿孔皮革老化是验货重点。",
    advice:"走量款，单件利润薄，靠周转。"},
  { id:"n5", brand:"hermes", cat:"包袋", series:"Herbag", name:"Herbag 31 帆布", spec:"帆布 + 皮革 · 黑/卡其",
    price:20000, low:9500, high:14000, ret:58, heat:62, trend:-2,
    tags:["入门款","替换袋"],
    desc:"最便宜的正装感爱马仕，帆布耐造。二手价约为公价 5~7 折，无溢价。",
    points:["可换袋设计是卖点","刻印清晰附件全者好出手"],
    risk:"帆布染色、皮革磨白影响价格。",
    advice:"小额快跑品类，别压库存。"},
  { id:"n6", brand:"chanel", cat:"包袋", series:"Classic Flap", name:"CF 小号 黑金", spec:"鱼子酱皮 · 金扣",
    price:92000, low:42000, high:56000, ret:53, heat:91, trend:-1,
    tags:["硬通货","经典尺寸"],
    desc:"CF 小号 2026 年公价已破 9 万，二手回收在 4.2~5.6 万，黑色款保值率常年 85% 以上。",
    points:["鱼子酱皮比羊皮耐造溢价约 1000~2000","大全套与单包差价近万元"],
    risk:"链条脱色、四角磨损是扣价重灾区。",
    advice:"黑金现货不愁卖，季节色慎收。"},
  { id:"n7", brand:"chanel", cat:"包袋", series:"Classic Flap", name:"CF 大号 黑金", spec:"鱼子酱皮 · 金扣",
    price:102000, low:45000, high:62000, ret:52, heat:84, trend:-2,
    tags:["大尺寸"],
    desc:"大号受众多为通勤客，流通略慢于中号，价格结构与中号一致。",
    points:["男客群体需求稳定","双链可肩背实用性强"],
    risk:"大尺寸成色差的件更难出手。",
    advice:"报价贴中位数，别按上限收。"},
  { id:"n8", brand:"chanel", cat:"包袋", series:"Gabrielle", name:"流浪包 中号 黑色", spec:"小牛皮 · 金扣",
    price:45000, low:21000, high:28000, ret:54, heat:76, trend:-4,
    tags:["热度回落"],
    desc:"流浪包热度从高点回落，2026 年回收在 2.1~2.8 万，黑金基本款最稳。",
    points:["硬挺结构不易变形","双色链条可调节"],
    risk:"麂皮款染色难处理，扣价狠。",
    advice:"只收黑/黑金基本款，走量为主。"},
  { id:"n9", brand:"chanel", cat:"包袋", series:"方胖子", name:"金球方胖子 黑色", spec:"小羊皮 · 可调金链",
    price:52000, low:29000, high:36000, ret:62, heat:88, trend:2,
    tags:["热门","小包"],
    desc:"金球 adjustable 链条设计热度持续，是方胖子里的硬通货，回收价明显高于普通方胖子。",
    points:["金球款流通速度极快","黑金配色保值最佳"],
    risk:"羊皮划痕敏感，验货看四角。",
    advice:"紧俏款，收货可贴上限，快进快出。"},
  { id:"n10", brand:"chanel", cat:"包袋", series:"Coco Handle", name:"Coco Handle 中号", spec:"鱼子酱/老花 · 黑",
    price:44000, low:18000, high:26000, ret:50, heat:70, trend:-2,
    tags:["通勤"],
    desc:"手柄 + 肩带双背设计，通勤客基础款，回收约公价 4~6 折。",
    points:["老花款比纯黑流通略好","手柄皮革状态决定估价"],
    risk:"手柄根部开裂是常见问题。",
    advice:"标准走量款，按区间中位收。"},
  { id:"n11", brand:"lv", cat:"包袋", series:"Metis", name:"邮差包 Metis 老花", spec:"涂层帆布 · 老花",
    price:20000, low:11200, high:14800, ret:65, heat:80, trend:-5,
    tags:["通勤","走量"],
    desc:"老花邮差是 LV 通勤线的销量王，二手价 1.1~1.5 万，变现速度快。",
    points:["翻盖磁扣结构耐用","附原肩带者溢价 10%"],
    risk:"包角磨损、内衬粘皮常见。",
    advice:"全网流通量大，收价贴下限易周转。"},
  { id:"n12", brand:"lv", cat:"包袋", series:"Dauphine", name:"达芙妮 MM 老花", spec:"涂层帆布 + 皮革 · 老花",
    price:32500, low:6200, high:9500, ret:24, heat:58, trend:-18,
    tags:["暴跌款","高危"],
    desc:"2026 年 LV 二手重灾区：公价 3.25 万回收仅 6~9 千，价值蒸发超 70%，切勿高位接手。",
    points:["仅适合极低价捡漏","原价购入者损失惨重"],
    risk:"行情单边下行，库存即亏损。",
    advice:"只按 6 千级别收，别信卖家讲的原价故事。"},
  { id:"n13", brand:"lv", cat:"包袋", series:"Petite Malle", name:"小硬盒 Petite Malle", spec:"涂层帆布 · 老花",
    price:41800, low:8000, high:12500, ret:24, heat:52, trend:-12,
    tags:["暴跌款","派对包"],
    desc:"小硬盒二手 8 千上下就能拿下，从爆跌至公价 2~3 折，属高折价藏品。",
    points:["内衬小羊皮状态是关键","铆钉五金完整度重要"],
    risk:"受众极窄，周转周期长。",
    advice:"不作为主营品类，遇低价可玩票。"},
  { id:"n14", brand:"lv", cat:"包袋", series:"Alma", name:"Alma BB 老花", spec:"涂层帆布 · 老花",
    price:16000, low:6500, high:9500, ret:50, heat:66, trend:-6,
    tags:["经典壳型"],
    desc:"贝壳包经典款，热度中等，二手稳定在 6.5~9.5 千。",
    points:["漆皮/帆布两个版本行情接近","手柄染色是通病"],
    risk:"米色手柄氧化发黄扣价明显。",
    advice:"区间内收，别为成色一般的件加价。"},
  { id:"n15", brand:"lv", cat:"包袋", series:"Speedy", name:"Speedy 30 肩带款 老花", spec:"涂层帆布 · 老花",
    price:21000, low:9000, high:13000, ret:52, heat:78, trend:-4,
    tags:["通勤","走量"],
    desc:"带肩带款比无带款流通更好，30cm 适合通勤客群，二手 9 千~1.3 万。",
    points:["肩带款溢价约 15%~20%","蜜蜡化提手属正常范围"],
    risk:"内衬粘皮、锁头损坏常见。",
    advice:"标准走量款，收下限卖中位。"},
  { id:"n16", brand:"dior", cat:"包袋", series:"Lady Dior", name:"五格戴妃 黑羊皮", spec:"小羊皮 · 金/银扣",
    price:46000, low:23000, high:29000, ret:57, heat:74, trend:-3,
    tags:["经典款"],
    desc:"五格比三格行情略高，藤格纹 + 徽章吊饰完整度影响价格，回收 2.3~2.9 万。",
    points:["原装吊饰齐全溢价 5%~10%","羊皮易划痕，成色决定档位"],
    risk:"翻新过的羊皮包要警惕。",
    advice:"吊饰缺失的按 9 折内收。"},
  { id:"n17", brand:"dior", cat:"包袋", series:"30 Montaigne", name:"蒙田包 老花", spec:"涂层帆布 · 老花蓝",
    price:36000, low:16000, high:22500, ret:53, heat:72, trend:-4,
    tags:["通勤"],
    desc:"蒙田包热度平稳，CD 方扣款是识别点，二手 1.6~2.25 万。",
    points:["Box 皮款比老花略保值","磁扣五金磨损常见"],
    risk:"包型挺度下降（压瘪）难修复。",
    advice:"按区间中位操作，快进快出。"},
  { id:"n18", brand:"dior", cat:"包袋", series:"Bobby", name:"Bobby 中号 老花", spec:"帆布 + 皮革 · 老花",
    price:29000, low:12000, high:17000, ret:48, heat:62, trend:-5,
    tags:["热度回落"],
    desc:"Bobby 热度已过峰，回收落在 1.2~1.7 万，只建议低价收。",
    points:["双肩带设计可多种背法","黑蓝老花最易出手"],
    risk:"非热门期库存风险高。",
    advice:"谨慎收货，报价贴下限。"},
  { id:"n19", brand:"gucci", cat:"包袋", series:"GG Marmont", name:"Marmont 中号链条", spec:"天鹅绒/皮革 · 黑",
    price:19500, low:7500, high:10800, ret:47, heat:70, trend:-6,
    tags:["走量"],
    desc:"Marmont 是古驰常青款，但整体折价明显，二手 7.5 千~1.08 万。",
    points:["双 G logo 五金状态是验货点","黑色最易出手"],
    risk:"天鹅绒款沾灰难清理。",
    advice:"引流走量款，收价贴下限。"},
  { id:"n20", brand:"gucci", cat:"包袋", series:"Dionysus", name:"酒神包 中号", spec:"老花帆布 · 虎头扣",
    price:24000, low:6800, high:9600, ret:34, heat:62, trend:-8,
    tags:["热度下降"],
    desc:"前几年爆款，2026 年回收仅公价 3~4 折，热度下行期慎入。",
    points:["虎头五金完整度是关键","链条可拆卸双背"],
    risk:"行情下行通道，库存贬值风险高。",
    advice:"只在 7 千以下收，快周转。"},
  { id:"n21", brand:"ysl", cat:"包袋", series:"Niki", name:"Niki 中号 链条邮差", spec:"褶皱小牛皮 · 黑",
    price:19800, low:9500, high:13000, ret:57, heat:80, trend:-3,
    tags:["常青款","走量"],
    desc:"YSL 最能打的款，褶皱皮耐造，二手 9.5 千~1.3 万，流通稳定。",
    points:["油腻褶皱皮抗磨耐造","银链款比金链款流通好"],
    risk:"内衬开线、链条褪色常见。",
    advice:"黑色中号是安全牌，按区间中位收。"},
  { id:"n22", brand:"ysl", cat:"包袋", series:"LOULOU", name:"LOULOU 中号", spec:"Y 型绗缝皮 · 黑",
    price:21500, low:8500, high:12000, ret:48, heat:70, trend:-4,
    tags:["走量"],
    desc:"Y 型绗缝辨识度高，二手 8.5 千~1.2 万，弱于 Niki 但流通尚可。",
    points:["小号比中号更受年轻客群欢迎","绗缝线开裂是验货重点"],
    risk:"边角磨损后修复价值低。",
    advice:"走量款，贴下限收。"},
  { id:"n23", brand:"loewe", cat:"包袋", series:"Puzzle", name:"Puzzle 中号 几何包", spec:"小牛皮 · 焦糖/黑",
    price:24500, low:8300, high:11600, ret:41, heat:72, trend:-4,
    tags:["折叠设计"],
    desc:"罗意威当家款，几何折叠设计，二手 8.3 千~1.16 万，焦糖色最走量。",
    points:["多way背法是卖点","焦糖/棕色系流通最好"],
    risk:"皮褶处磨损、内衬变形常见。",
    advice:"中位收中位卖，利润薄靠周转。"},
  { id:"n24", brand:"loewe", cat:"包袋", series:"Gate", name:"Gate 小号 马鞍扣", spec:"颗粒皮 · 焦糖",
    price:16500, low:6000, high:9000, ret:46, heat:62, trend:-4,
    tags:["腋下包"],
    desc:"Gate 热度中等，回收 6~9 千，视马鞍扣五金完整度定档。",
    points:["颗粒皮耐磨","结绳细节完整者好出手"],
    risk:"细带易磨损断裂。",
    advice:"小额款，随行就市。"},
  { id:"n25", brand:"celine", cat:"包袋", series:"Triomphe", name:"凯旋门腋下包", spec:"光面牛皮 · 黑",
    price:23000, low:8000, high:10500, ret:39, heat:74, trend:-3,
    tags:["腋下包","走量"],
    desc:"凯旋门扣是赛琳当今识别核心，腋下款二手 8 千~1.05 万，年轻客群流通好。",
    points:["光面皮划痕影响价格大","五金镀层褪色常见"],
    risk:"金属扣划痕修复难。",
    advice:"黑色现货好出手，贴下限收。"},
  { id:"n26", brand:"celine", cat:"包袋", series:"Triomphe", name:"老花凯旋门托特", spec:"帆布 + 皮革 · 老花",
    price:19500, low:6500, high:9200, ret:40, heat:68, trend:-5,
    tags:["通勤","走量"],
    desc:"赛琳老花托特通勤属性强，二手 6.5~9.2 千，走量稳定。",
    points:["帆布耐磨抗造","内袋完整性影响估价"],
    risk:"底部四角磨损是通病。",
    advice:"引流款，快速周转为主。"},

  /* ===== 2026-10 扩充 · 腕表 ===== */
  { id:"n27", brand:"patek", cat:"腕表", series:"Nautilus", name:"鹦鹉螺 5712A 月相", spec:"精钢 · 蓝盘 · 月相动力储存",
    price:320000, low:780000, high:880000, trend:3, ret:260, heat:90,
    tags:["停产","超公价","顶奢钢王"],
    desc:"5712 是鹦鹉螺家族的月相款，停产加持后与 5711 并列钢表之王，全套行情 78~88 万。",
    points:["月相 + 动力储存小盘辨识度高","全套与裸表差价可达十几万","原厂保卡是硬门槛"],
    risk:"后镶改、拼装件流通于市，鉴定门槛极高。",
    advice:"只收有原始凭证的件，交易走检测流程。"},
  { id:"n28", brand:"patek", cat:"腕表", series:"Nautilus", name:"鹦鹉螺 5980/1A 计时", spec:"精钢 · 蓝盘 · 计时",
    price:400000, low:950000, high:1150000, trend:4, ret:263, heat:88,
    tags:["停产","计时","超公价"],
    desc:"钢壳计时鹦鹉螺，2026 年回收 95~115 万，是钢表金字塔尖，流通周期 1~7 天。",
    points:["单一表盘计时布局独特","停产款存量持续收缩"],
    risk:"维修成本极高，机芯状态需专业检测。",
    advice:"资产型货品，有货即收，利润空间大。"},
  { id:"n29", brand:"patek", cat:"腕表", series:"Aquanaut", name:"手雷 5167A 黑盘", spec:"精钢 · 黑色复合材质盘",
    price:233600, low:360000, high:460000, ret:175, heat:91,
    tags:["超公价","运动款"],
    desc:"百达翡丽运动线第二支柱，2026 年 95 新全套 36~46 万，保值率 154%~197%。",
    points:["橡胶表带老化是常见扣价项","全套附件溢价 10%~25%"],
    risk:"非官方开盖压价严重。",
    advice:"硬通货，坚定报价。"},
  { id:"n30", brand:"patek", cat:"腕表", series:"Aquanaut", name:"手雷 5164A 两地时", spec:"精钢 · 黑盘 · 两地时",
    price:260000, low:480000, high:580000, ret:204, heat:82, trend:2,
    tags:["超公价","两地时"],
    desc:"手雷两地时款，比 5167 更稀缺，回收 48~58 万。",
    points:["双时区功能受商务客青睐","表带更换历史影响估价"],
    risk:"功能复杂，机芯检测不可省。",
    advice:"稀缺件，报价可贴上限。"},
  { id:"n31", brand:"patek", cat:"腕表", series:"Twenty~4", name:"Twenty~4 钢款 7300", spec:"精钢 · 自动 · 女款",
    price:158000, low:95000, high:135000, ret:72, heat:68, trend:-2,
    tags:["女款"],
    desc:"PP 女款自动机械，无钻钢款回收 9.5~13.5 万，是女表里最保值的系列之一。",
    points:["钢款无钻流通好于金款","原镶钻版本行情另计"],
    risk:"女表受众相对窄，周转略慢。",
    advice:"收全套件，按区间中位走。"},
  { id:"n32", brand:"patek", cat:"腕表", series:"Twenty~4", name:"Twenty~4 满钻 满天星", spec:"精钢 · 原厂满钻 · 女款",
    price:320000, low:260000, high:340000, ret:94, heat:85, trend:1,
    tags:["满天星","原厂满钻","女款"],
    desc:"俗称'满天星'的原厂满钻 Twenty~4，原钻与后镶钻差价巨大，原厂款回收 26~34 万，后镶钻仅 5~10 万。",
    points:["认准原厂镶钻证书与刻印","钻石切工与排镶工艺是鉴定点"],
    risk:"市场后镶钻冒充原厂钻极多，看走眼差价 20 万+。",
    advice:"务必送专业鉴定，原厂件利润可观。"},
  { id:"n33", brand:"patek", cat:"腕表", series:"Calatrava", name:"卡拉卓华 5227G", spec:"白金 · 白面 · 大三针",
    price:300000, low:160000, high:270000, ret:72, heat:65, trend:0,
    tags:["正装","白金"],
    desc:"正装表标杆，回收价约公价 45%~70%，极看附件与机芯状态。",
    points:["翻盖底盖设计受欢迎","全套保养记录可提价"],
    risk:"正装款受众窄，复杂款鉴定要求高。",
    advice:"全套件贴上限收，裸表慎入。"},
  { id:"n34", brand:"rolex", cat:"腕表", series:"GMT-Master II", name:"百事圈 GMT 126710BLRO", spec:"精钢 · 红蓝圈 · 五珠链",
    price:97500, low:110000, high:170000, ret:144, heat:89,
    tags:["超公价","GMT"],
    desc:"红蓝圈 GMT 人气款，回收 11~17 万区间浮动，红蓝陶圈配色辨识度最高。",
    points:["五珠链 Oysterflex 版本行情不同","绿盘款（雪碧圈）另计"],
    risk:"圈口划伤、保卡年份影响明显。",
    advice:"热门 GMT，报价看当周行情。"},
  { id:"n35", brand:"rolex", cat:"腕表", series:"Datejust", name:"日志型 41 钢款", spec:"精钢 · 光圈/狗牙圈 · 41mm",
    price:88000, low:42000, high:58000, ret:57, heat:82,
    tags:["正装","折价明显"],
    desc:"日志 41 是劳力士产量最大系列，二手仅公价 5~6 折，2026 年行情依旧疲软。",
    points:["流通量大出手快","间金款回收略好于全钢"],
    risk:"只适合自用，别指望保值。",
    advice:"低价收快周转，别压库存。"},
  { id:"n36", brand:"rolex", cat:"腕表", series:"Datejust", name:"日志型 满钻 满天星（后镶钻）", spec:"精钢/间金 · 后镶满钻",
    price:120000, low:180000, high:280000, ret:192, heat:78,
    tags:["满天星","后镶钻","女款为主"],
    desc:"市场俗称'满天星日志'，原厂满钻极贵（30~80 万），后镶钻版本 18~28 万流通最广，需分清。",
    points:["后镶钻看钻石净度与排镶工艺","间金后镶比全钢后镶保值"],
    risk:"后镶钻官方不保修，转手需告知买家。",
    advice:"利润款，但必须如实标注后镶属性。"},
  { id:"n37", brand:"vacheron", cat:"腕表", series:"Overseas", name:"纵横四海 4500V 蓝盘", spec:"精钢 · 蓝盘 · 41mm",
    price:172000, low:140000, high:165000, ret:89, heat:87,
    tags:["三大钢王","快拆表带"],
    desc:'"三大钢王"中唯一低于公价的选项，95 新全套 14~16.5 万，保值率 82%~96%，性价比之选。',
    points:["三表带快拆系统实用","日内瓦印记机芯"],
    risk:"蓝盘最受欢迎，银盘/黑盘回收低 1~2 万。",
    advice:"稳步上行的款，全套件优先。"},
  { id:"n38", brand:"vacheron", cat:"腕表", series:"Overseas", name:"纵横四海 4520V", spec:"精钢 · 蓝盘 · 新款",
    price:196000, low:175000, high:205000, ret:97, heat:80,
    tags:["新款"],
    desc:"4500V 的迭代新款，折价小、流通持续向好，回收 17.5~20.5 万。",
    points:["尺寸更大更现代","机芯升级"],
    risk:"新款存量少，真伪核验要严。",
    advice:"行情上行期，可贴上限收。"},
  { id:"n39", brand:"cartier", cat:"腕表", series:"Tank", name:"Tank Must 石英", spec:"精钢 · 黑/白面",
    price:21000, low:9500, high:14000, ret:56, heat:70,
    tags:["正装","石英"],
    desc:"坦克入门款，辨识度极高的方形壳，二手 9.5 千~1.4 万，出手快。",
    points:["石英机芯省心","男女通吃受众广"],
    risk:"石英机芯老化、表冠损坏常见。",
    advice:"流通效率高，小额快跑。"},

  /* ===== 2026-10 扩充 · 首饰 ===== */
  { id:"n40", brand:"vca", cat:"首饰", series:"Alhambra", name:"黑玛瑙四叶草中号", spec:"18K 金 + 黑玛瑙",
    price:30000, low:19000, high:26000, ret:75, heat:82,
    tags:["经典款"],
    desc:"红玉髓之外的第二大流通色，黑玛瑙冷艳百搭，回收 1.9~2.6 万。",
    points:["黑玛瑙忌油污，品相差异大","配原盒证书溢价明显"],
    risk:"黑玛瑙磕碰崩边难修复。",
    advice:"与红玉髓并列硬通货，优先收全附件。"},
  { id:"n41", brand:"cartier_j", cat:"首饰", series:"Juste un Clou", name:"钉子手镯 无钻", spec:"18K 玫瑰金/黄金",
    price:48000, low:26000, high:34000, ret:62, heat:78,
    tags:["经典款"],
    desc:"卡地亚钉子系列，与 LOVE 并列两大手镯王牌，无钻款回收 2.6~3.4 万。",
    points:["玫瑰金款最走量","弯折变形是最大杀手"],
    risk:"检测受力变形后修复价值大打折扣。",
    advice:"经典款流通稳，中位收中位卖。"},
  { id:"n42", brand:"bvlgari", cat:"首饰", series:"Serpenti", name:"灵蛇手镯 黑陶瓷", spec:"黑陶瓷 + 18K 金",
    price:26000, low:13000, high:19000, ret:61, heat:74,
    tags:["走量"],
    desc:"灵蛇手镯是宝格丽首饰线走量王，黑陶瓷款回收 1.3~1.9 万。",
    points:["陶瓷磕碰难修复","金头部分克重影响底价"],
    risk:"陶瓷碎裂基本报废。",
    advice:"验货看陶瓷完整性，走量为主。"},
  { id:"n43", brand:"tiffany", cat:"首饰", series:"T1", name:"T1 宽版手镯", spec:"18K 玫瑰金/黄金",
    price:32000, low:15000, high:21000, ret:57, heat:66,
    tags:["新款"],
    desc:"蒂芙尼当家中生代款式，T 造型简洁，回收 1.5~2.1 万，行情平稳。",
    points:["宽版比窄版保值","铰链松紧是验货点"],
    risk:"铰链松动修复成本高。",
    advice:"标准走量款，贴区间中位操作。"}
];

/* ---------- 行情/指数模块 ---------- */
const INDEX = {
  name: "奢眼二手奢侈品价格指数",
  base: 1000,
  points: [
    { m: "2024-09", v: 1000 }, { m: "2024-12", v: 1012 }, { m: "2025-03", v: 1005 },
    { m: "2025-06", v: 988 },  { m: "2025-09", v: 972 },  { m: "2025-12", v: 965 },
    { m: "2026-03", v: 981 },  { m: "2026-06", v: 994 },  { m: "2026-09", v: 1002 }
  ],
  catTrend: [
    { name: "包袋", v: 1.8, desc: "爱马仕/香奈儿拉动，LV 拖累" },
    { name: "腕表", v: -6.4, desc: "钢款持续回调，全金款承压" },
    { name: "首饰", v: 2.6, desc: "梵克雅宝红玉髓、卡地亚 LOVE 支撑" }
  ]
};

/* 保值率梯队（2026年二手市场） */
const RETENTION_TIERS = [
  { tier: "T0 硬通货", ret: "110%+",  brands: ["爱马仕 BKC", "百达翡丽鹦鹉螺"], color: "#B8763E",
    note: "二级市场溢价，可跑赢通胀，属于资产级标的" },
  { tier: "T1 稳健",   ret: "85%~110%", brands: ["劳力士热门钢款", "爱马仕入门款"], color: "#C0392B",
    note: "流通最快，短期波动大但长期抗跌" },
  { tier: "T2 保值",   ret: "60%~85%",  brands: ["香奈儿 CF/2.55", "卡地亚 LOVE 素金", "梵克雅宝四叶草"], color: "#D68910",
    note: "经典款表现稳定，季节款/材质差的会明显掉档" },
  { tier: "T3 一般",   ret: "40%~60%",  brands: ["LV 老花", "迪奥", "欧米茄", "宝格丽", "蒂芙尼"], color: "#7D8B99",
    note: "靠流量和成色吃饭，看款式热度" },
  { tier: "T4 低保值", ret: "<40%",     brands: ["轻奢品牌", "时装表", "银饰", "季节限定款"], color: "#95A5A6",
    note: "不建议长期持有，折价重灾区" }
];

/* 回收计价模型（商家核心工具） */
const PRICING_MODEL = {
  steps: [
    { k: "① 品类基准行情价", w: "款型热度定档", desc: "按品牌 + 系列 + 尺寸 + 材质的当日行情基准，是本模型的主锚点" },
    { k: "② 成色系数", w: "0.75~1.00", desc: "99新/95新足额；磨损、划痕、变形、翻新按档折价。正常使用痕迹与人为损伤分开评估" },
    { k: "③ 附件系数", w: "0.88~1.22", desc: "全套（盒/防尘袋/票/保卡）加 8%~22%；缺失保卡折价 12%~25%；裸件折价最大" },
    { k: "④ 材质与配件原装度", w: "扣减项", desc: "五金后配/替换、内衬翻新、局部补漆、高仿拼接均需扣减，是高频隐性问题" },
    { k: "⑤ 当日实时行情联动", w: "随行就市", desc: "按当日行情浮动，不沿用老旧行情虚高引流" }
  ],
  example: {
    title: "计价示例 · 香奈儿 CF 中号 黑金（95新全套）",
    rows: [
      ["① 品类基准行情价", "¥ 42,000"],
      ["② 成色系数（95新足额）", "× 1.00"],
      ["③ 附件系数（全套齐全）", "× 1.10"],
      ["④ 原装度扣减（无）", "- ¥ 0"],
      ["⑤ 当日行情联动", "× 1.00"],
      ["回收参考报价", "¥ 46,200"]
    ],
    note: "仅为计价逻辑演示，不构成报价承诺。最终以实物检测与当日实时行情为准。"
  },
  risks: [
    { t: "先高后低", d: "线上以虚高报价引流，到店再编造理由连环压价", act: "严格执行「检测后报价 = 确认后结算」" },
    { t: "隐形扣费", d: "鉴定费、清洗费、损耗费名目繁多", act: "报价单分项列明，全部费用前置公示" },
    { t: "夸大瑕疵", d: "刻意放大小瑕疵压价", act: "瑕疵量化拍照留证，成色定级有据可依" },
    { t: "价格倒挂", d: "按旧行情报价，收货即亏", act: "每日同步行情，报价带日期水印" },
    { t: "鉴定风险", d: "隐形翻新、局部补漆、高仿拼接肉眼难辨", act: "仪器 + 人工双重定级，编码全程溯源" }
  ]
};

/* ---------- 鉴定知识库 ---------- */
const AUTH_KB = [
  { brand: "chanel", name: "香奈儿", items: [
    { k: "身份卡字体", v: "正品数字采用「冷角八角形」专属字体，数字 4 瘦高、顶部宽于底部竖线，数字 0 呈八角形" },
    { k: "紫光荧光行", v: "紫光灯垂直照射文字区，正品有一行文字呈不同荧光效果，位置与序列号严格对应（7 位看第 1 位，8 位看前两位之和）" },
    { k: "镭射标", v: "身份卡背面序列号须与包内镭射标完全一致；正品镭射标数字边缘呈马赛克锯齿状，倾斜可见金蓝亮片交替" },
    { k: "NFC 芯片", v: "2021 年后新款改为内置 NFC 芯片，取代镭射标 + 身份卡" },
    { k: "菱格与链条", v: "菱格大小均匀，接缝处对齐；链条有分量、皮质穿插均匀；包内 CC 为刻印非印刷" }
  ]},
  { brand: "lv", name: "路易威登", items: [
    { k: "Monogram 对称", v: "老花图案对称且居中，经典款上老花图案不应被缝线切断" },
    { k: "Date Code", v: "如 FL0156，字母代表产地工厂，后 4 位代表生产年月。位置随年份变化" },
    { k: "五金与拉链", v: "拉链头带 LV 字样，金属呈特征性缎面质地；YKK 或 LV 拉链应顺滑无卡顿" },
    { k: "车线", v: "使用一致的芥末黄线，针距均匀，无跳线" },
    { k: "内衬", v: "Alcantara 或织物内衬质感高级，布纹清晰" }
  ]},
  { brand: "dior", name: "迪奥", items: [
    { k: "烫印字体", v: "正品「Christian Dior」粗细有致：字母 S 向右倾斜约 15°，h 竖线高出其他字母顶端，a 无翘脚且小肚子扁而下垂" },
    { k: "序列号形态", v: "采用专属衬线字体，数字凸起有立体感，0 呈偏瘦长鹅蛋形；仿品多用 Arial 等常见字体，扁平甚至带锯齿" },
    { k: "产地代码", v: "序列号首两位代表产地：01 = 意大利，04 = 法国。出现其他代码可直接判假" },
    { k: "底部支钉", v: "正品包底四颗金属支钉为矮胖圆锥体，顶部钝而圆润，形似卧倒的子弹头；仿品偏尖瘦刮手" },
    { k: "防伪体系", v: "2020 年起启用带二维码 + 12 位编码的新身份卡；2021 年复刻 Saddle 内置 NFC" }
  ]},
  { brand: "hermes", name: "爱马仕", items: [
    { k: "马鞍针法", v: "双针手缝，每针均匀且略微倾斜，绝无浮线、跳针、接缝重叠" },
    { k: "工匠钢印", v: "皮带下方有日期编码（字母代表年份 + 数字代表季度）与工匠印记" },
    { k: "锁头刻字", v: "锁头刻有「Hermès Paris」并带编号；皮拉链头与 clochette 均为皮革" },
    { k: "皮质气味", v: "Togo 皮柔软、天然不规则纹路，有自然皮革香，而非塑料味" },
    { k: "Turnlock 转锁", v: "开合顺滑，无涩感；Birkin / Kelly 的比例仿品极难复制" }
  ]},
  { brand: "vca", name: "梵克雅宝", items: [
    { k: "金珠排列", v: "正品每朵四叶草边缘有 10 颗浑圆立体的小金珠，大小一致、排列紧密" },
    { k: "刻印字体", v: "VCA 刻印字体清晰、间距均匀，边缘无毛刺" },
    { k: "材质判断", v: "红玉髓颜色饱和度自然，孔雀石纹路天然；仿品常颜色呆板或纹路重复" }
  ]},
  { brand: "cartier_j", name: "卡地亚首饰", items: [
    { k: "刻印规范", v: "字体、间距、深浅、位置均有标准，需用宝石显微镜核验是否符合原厂规范" },
    { k: "材质纯度", v: "光谱材质检测仪无损检测贵金属成分，18K 金纯度读数可直接查看" },
    { k: "工艺特征", v: "显微镜下核验边缘打磨痕迹与镶嵌工艺是否达原厂水平" },
    { k: "螺丝造型", v: "LOVE 系列螺丝凹槽深浅一致，边缘锐利无毛边" }
  ]},
  { brand: "rolex", name: "劳力士", items: [
    { k: "保卡逻辑", v: "带有效在保保卡可溢价 10%~15%；缺保卡折价 12%~25%；全套齐全享 8%~22% 溢价" },
    { k: "机芯状态", v: "走时检测仪 + 防水测试 + 机芯拆解检测，确认无翻新、无拼装" },
    { k: "表壳厚度", v: "多次深度抛光会削减表壳厚度，直接影响二手估值。卖表前不要自行抛光" },
    { k: "序列号与型号", v: "表耳间序列号须与保卡一致，型号（如 126610LN）与配置（盘色/圈色）匹配" }
  ]},
  { brand: "universal", name: "通用逻辑", items: [
    { k: "交叉验证原则", v: "至少两个维度相互印证：身份卡/镭射标 + 五金刻印 + NFC/气味，单看小票或防尘袋极易被高仿迷惑" },
    { k: "一票否决项", v: "序列号与保卡/镭射标不一致、产地代码错误、烫印字体明显不符 —— 出现任一项直接判定" },
    { k: "价格红线", v: "远低于市场价 → 假货概率极高。Birkin 卖 2000 欧一定是假的" },
    { k: "渠道为王", v: "非专柜购买即便专业人士也难凭肉眼判断，权威第三方鉴定报告才是最终依据" }
  ]}
];

/* ---------- 选购决策：预算 × 场景 ---------- */
const BUDGETS = [10000, 20000, 30000, 50000, 80000, 150000, 300000];

const SCENARIOS = [
  { id: "invest", name: "投资保值", icon: "▲", desc: "看重转手溢价与流通速度" },
  { id: "daily",  name: "日常通勤", icon: "▤", desc: "看重耐造、容量、使用频次" },
  { id: "social", name: "社交场合", icon: "✧", desc: "看重辨识度与身份标签" },
  { id: "gift",   name: "送礼需求", icon: "◈", desc: "看重品牌认知度与仪式感" },
  { id: "entry",  name: "第一次买大牌", icon: "❍", desc: "看重性价比与低风险" }
];

const RECOMMEND_RULES = [
  { scen: "invest", budget: 150000, label: "爱马仕 Birkin 25 金刚色", pid: "h1", why: "二级市场硬通货，金刚色 + 25cm 是溢价最猛组合，转手周期通常不超一周。注意配货成本。" },
  { scen: "invest", budget: 200000, label: "劳力士 熊猫迪 116500LN", pid: "r3", why: "回收价反超公价约 60%，流通性极强。但需注意已从峰值回落，不宜高位追。" },
  { scen: "invest", budget: 50000,  label: "香奈儿 CF 中号 黑金", pid: "c1", why: "市场定海神针，黑金款二手保值率可达 90%~110%，黑金三年增值约 37%，流通以天计算。" },
  { scen: "invest", budget: 80000,  label: "爱马仕 Picotin 18 菜篮子", pid: "h5", why: "低配货门槛的硬通货，适合作为进入爱马仕体系的跳板，金刚色好出货。" },
  { scen: "invest", budget: 10000,  label: "LV Neverfull 中号 老花", pid: "l2", why: "九成新附件齐全款保值率约 88%，存量最大、流通最快，薄利多销的最佳标的。" },

  { scen: "daily", budget: 20000, label: "LV Speedy B25 老花", pid: "l3", why: "轻便抗造、防水防刮，日常使用频次高，维修成本低，是通勤第一只包的默认选项。" },
  { scen: "daily", budget: 30000, label: "爱马仕 Picotin 18 菜篮子", pid: "h5", why: "皮料柔软、容量大、无需刻意保养，通勤场景适配度高，且保值率近 100%。" },
  { scen: "daily", budget: 50000, label: "欧米茄 海马 300 米", pid: "o1", why: "通勤热门钢款，流通稳定，二手性价比突出，第四代 8800 机芯款最值得入手。" },
  { scen: "daily", budget: 80000, label: "卡地亚 LOVE 无钻宽版手镯", pid: "cj1", why: "素金款不怕磕碰，可长期佩戴，且是首饰里的硬通货，回收可达原价 85% 左右。" },

  { scen: "social", budget: 150000, label: "爱马仕 Birkin 25 / Kelly 28", pid: "h2", why: "顶级社交场的身份标签，低调但懂的人自然懂，是圈层确认的硬通货。" },
  { scen: "social", budget: 80000, label: "香奈儿 CF 中号 黑金", pid: "c1", why: "双 C 标志辨识度无敌，商务与下午茶场景皆宜，社交属性与保值性最均衡。" },
  { scen: "social", budget: 30000, label: "迪奥 Lady Dior 三格", pid: "d1", why: "戴妃包名媛风格，晚宴辨识度极高。代价是羊皮极易划伤，需要精心保养。" },
  { scen: "social", budget: 50000, label: "梵克雅宝 四叶草五花手链", pid: "v1", why: "高珠里最不容易出错的社交单品，红玉髓常年缺货，佩戴与保值兼得。" },

  { scen: "gift", budget: 20000, label: "梵克雅宝 四叶草单花项链 红玉髓", pid: "v2", why: "品牌认知度高、寓意好、尺码无风险，是送礼最稳妥的选择，保值率 75%~85%。" },
  { scen: "gift", budget: 30000, label: "卡地亚 LOVE 无钻窄版手镯", pid: "cj2", why: "玫瑰金窄版门槛友好，卡地亚品牌背书强，送礼体面且对方可长期佩戴。" },
  { scen: "gift", budget: 10000, label: "蒂芙尼 T 系列微笑项链", pid: "t1", why: "18K 金素金款流通极快，年轻客群接受度高，价格友好。切忌选银饰。" },
  { scen: "gift", budget: 50000, label: "卡地亚 蓝气球 33mm 间金", pid: "ct1", why: "女士腕表标杆，婚嫁与商务场景通吃，33mm 间金机械款流通速度快。" },

  { scen: "entry", budget: 10000, label: "LV Neverfull 中号 老花", pid: "l2", why: "1.5 万级公价，二手 0.8~1.2 万即可拿下，是「人生第一只大牌包」的默认答案，几乎不贬值。" },
  { scen: "entry", budget: 20000, label: "LV Speedy / 蒂芙尼 T 系列", pid: "l3", why: "同价位里流通性最好的组合，出手容易，试错成本低。" },
  { scen: "entry", budget: 30000, label: "爱马仕 Picotin 18 菜篮子", pid: "h5", why: "零配货门槛进入爱马仕体系的最好方式，金刚色转手容易，保值近 100%。" },
  { scen: "entry", budget: 50000, label: "香奈儿 2.55 小号 做旧牛皮", pid: "c2", why: "预算 8 万以下的稳妥选择，公价低于 CF 约 3000~5000 元，低调且保值 70%~80%。" },

  { scen: "invest", budget: 30000, label: "梵克雅宝 四叶草五花手链 红玉髓", pid: "v1", why: "小资金里保值表现最好的首饰标的，常年缺货，流通速度快，综合保值率 80%+。" },
  { scen: "invest", budget: 100000, label: "劳力士 黑水鬼 126610LN", pid: "r2", why: "流通最快的入门钢款之一，接近公价成交，风险最低的腕表标的，适合作为资金池主力。" },
  { scen: "daily", budget: 10000, label: "浪琴 康卡斯 潜水", pid: "lg1", why: "入门潜水表性价比之选，1.5 万公价、二手 0.6~0.8 万，适合日常佩戴不心疼。" },
  { scen: "gift", budget: 80000, label: "宝格丽 Serpenti 灵蛇满钻戒指", pid: "b2", why: "蛇头设计辨识度高，满钻款保值率 65%~75%，适合追求设计感的送礼场景。" }
];

/* 避坑清单 */
const PITFALLS = [
  { t: "预算分配", k: "别为配货买垃圾", d: "爱马仕配货商品本身不保值，丝巾转手折价高。优先选成衣/珠宝类配货，或直接接受二手溢价。" },
  { t: "款式选择", k: "不买超 35cm 大尺寸", d: "Birkin 35 以上、超大托特难转手，体积还增加仓储与运输成本。" },
  { t: "颜色选择", k: "冷门色折价快", d: "亮蓝、玫红、荧光色等高调色二手流通慢。金刚色（黑/金棕/大象灰）才是安全牌。" },
  { t: "材质选择", k: "羊皮 vs 帆布差一倍", d: "Lady Dior 小羊皮、香奈儿小羊皮划痕直接掉档；白贝母遇水发黄、孔雀石硬度低，首饰材质梯度务必记牢。" },
  { t: "附件完整度", k: "保卡比表壳更值钱", d: "劳力士缺保卡折价 12%~25%；全套可溢价 8%~22%。收包收表第一件事：点附件。" },
  { t: "真伪风险", k: "至少两个维度交叉验证", d: "单看小票或防尘袋极易被高仿迷惑。序列号、五金刻印、NFC 至少两项相互印证。" },
  { t: "价格红线", k: "远低于市场价就是假", d: "Birkin 卖 2000 欧一定是假的。低价是最大的红旗。" },
  { t: "养护禁忌", k: "卖表前别自己抛光", d: "多次深度抛光削减表壳厚度，直接影响估值。保留原始状态更有利于鉴定定价。" },
  { t: "行情风险", k: "别用三个月前的报价", d: "劳力士二手均价两年跌约 11.5%，LV 部分爆款腰斩。报价必须带当日日期水印。" }
];

/* ---------- 首页行情速览 ---------- */
const MOVERS = {
  up: [
    { pid: "h3", name: "Mini Kelly 二代", v: "+5.0%", note: "迷你尺寸热度持续" },
    { pid: "p1", name: "鹦鹉螺 5711/1A", v: "+4.3%", note: "停产稀缺，企稳回升" },
    { pid: "cj1", name: "卡地亚 LOVE 宽版", v: "+3.0%", note: "素金硬通货，金价支撑" }
  ],
  down: [
    { pid: "r4", name: "绿金迪 116508", v: "-15.0%", note: "全金款承压最重" },
    { pid: "l1", name: "LV Carryall 小号", v: "-12.0%", note: "爆款退潮，波动剧烈" },
    { pid: "r5", name: "日志型 126334", v: "-10.0%", note: "正装款流动性走弱" }
  ]
};
